--Payment table
CREATE TABLE IF NOT EXISTS Payment(
	id SERIAL PRIMARY KEY,
	userId INT NOT NULL,
	bookingId INT NOT NULL,
	amount DOUBLE PRECISION DEFAULT 0,
	status BOOLEAN DEFAULT false,
	payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    	
	CONSTRAINT fk_user FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE
);

